# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AdminForm(object):
    def setupUi(self, AdminForm):
        AdminForm.setObjectName("AdminForm")
        AdminForm.resize(552, 455)
        self.frame = QtWidgets.QFrame(AdminForm)
        self.frame.setGeometry(QtCore.QRect(-20, -10, 591, 471))
        self.frame.setStyleSheet("QFrame{\n"
" border-image:url(:/img/bg.jpg);\n"
"}\n"
"    \n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.toSUI = QtWidgets.QPushButton(self.frame)
        self.toSUI.setEnabled(True)
        self.toSUI.setGeometry(QtCore.QRect(40, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.toSUI.setFont(font)
        self.toSUI.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(85, 85, 255);color: rgb(255, 255, 255);")
        self.toSUI.setObjectName("toSUI")
        self.toPUI = QtWidgets.QPushButton(self.frame)
        self.toPUI.setGeometry(QtCore.QRect(220, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.toPUI.setFont(font)
        self.toPUI.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(85, 85, 255);color: rgb(255, 255, 255);")
        self.toPUI.setObjectName("toPUI")
        self.toMUI = QtWidgets.QPushButton(self.frame)
        self.toMUI.setGeometry(QtCore.QRect(390, 70, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.toMUI.setFont(font)
        self.toMUI.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(85, 85, 255);color: rgb(255, 255, 255);")
        self.toMUI.setObjectName("toMUI")
        self.storeManR = QtWidgets.QPushButton(self.frame)
        self.storeManR.setGeometry(QtCore.QRect(220, 180, 139, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.storeManR.setFont(font)
        self.storeManR.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(85, 85, 255);color: rgb(255, 255, 255);")
        self.storeManR.setObjectName("storeManR")
        self.storeB = QtWidgets.QPushButton(self.frame)
        self.storeB.setGeometry(QtCore.QRect(400, 180, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.storeB.setFont(font)
        self.storeB.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(85, 85, 255);color: rgb(255, 255, 255);")
        self.storeB.setObjectName("storeB")
        self.storePR = QtWidgets.QPushButton(self.frame)
        self.storePR.setGeometry(QtCore.QRect(220, 290, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.storePR.setFont(font)
        self.storePR.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(85, 85, 255);color: rgb(255, 255, 255);")
        self.storePR.setObjectName("storePR")
        self.storeMemR = QtWidgets.QPushButton(self.frame)
        self.storeMemR.setGeometry(QtCore.QRect(400, 290, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.storeMemR.setFont(font)
        self.storeMemR.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(85, 85, 255);color: rgb(255, 255, 255);")
        self.storeMemR.setObjectName("storeMemR")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(50, 300, 133, 20))
        self.lineEdit.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.toMainUI = QtWidgets.QPushButton(self.frame)
        self.toMainUI.setGeometry(QtCore.QRect(470, 400, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.toMainUI.setFont(font)
        self.toMainUI.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(85, 85, 255);color: rgb(255, 255, 255);")
        self.toMainUI.setObjectName("toMainUI")

        self.retranslateUi(AdminForm)
        QtCore.QMetaObject.connectSlotsByName(AdminForm)

    def retranslateUi(self, AdminForm):
        _translate = QtCore.QCoreApplication.translate
        AdminForm.setWindowTitle(_translate("AdminForm", "Admin"))
        self.toSUI.setText(_translate("AdminForm", "Service"))
        self.toPUI.setText(_translate("AdminForm", "Provider"))
        self.toMUI.setText(_translate("AdminForm", "Member"))
        self.storeManR.setText(_translate("AdminForm", "StoreManagerReport"))
        self.storeB.setText(_translate("AdminForm", "StoreBill"))
        self.storePR.setText(_translate("AdminForm", "StoreProviderRecord"))
        self.storeMemR.setText(_translate("AdminForm", "StoreMemberRecord"))
        self.toMainUI.setText(_translate("AdminForm", "Return"))

import image_rc
