# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'member.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, proForm):
        proForm.setObjectName("Form")
        proForm.resize(507, 304)
        self.frame = QtWidgets.QFrame(proForm)
        self.frame.setGeometry(QtCore.QRect(-20, -10, 681, 501))
        self.frame.setStyleSheet("QFrame{\n"
" border-image:url(:/img/bg.jpg)\n"
"}\n"
"    \n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.search = QtWidgets.QPushButton(self.frame)
        self.search.setGeometry(QtCore.QRect(230, 210, 141, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.search.setFont(font)
        self.search.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(85, 85, 255);color: rgb(255, 255, 255);")
        self.search.setObjectName("search")
        self.delete_2 = QtWidgets.QPushButton(self.frame)
        self.delete_2.setGeometry(QtCore.QRect(50, 210, 131, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.delete_2.setFont(font)
        self.delete_2.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(85, 85, 255);color: rgb(255, 255, 255);")
        self.delete_2.setObjectName("delete_2")
        self.add = QtWidgets.QPushButton(self.frame)
        self.add.setGeometry(QtCore.QRect(50, 260, 75, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.add.setFont(font)
        self.add.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(85, 85, 255);color: rgb(255, 255, 255);")
        self.add.setObjectName("add")
        self.toAdminUI = QtWidgets.QPushButton(self.frame)
        self.toAdminUI.setGeometry(QtCore.QRect(230, 260, 75, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.toAdminUI.setFont(font)
        self.toAdminUI.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(85, 85, 255);color: rgb(255, 255, 255);")
        self.toAdminUI.setObjectName("toAdminUI")
        self.nameText = QtWidgets.QLineEdit(self.frame)
        self.nameText.setGeometry(QtCore.QRect(50, 40, 133, 20))
        self.nameText.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(255, 255, 255);")
        self.nameText.setObjectName("nameText")
        self.numberText = QtWidgets.QLineEdit(self.frame)
        self.numberText.setGeometry(QtCore.QRect(230, 40, 141, 20))
        self.numberText.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(255, 255, 255);")
        self.numberText.setObjectName("numberText")
        self.sdText = QtWidgets.QLineEdit(self.frame)
        self.sdText.setGeometry(QtCore.QRect(50, 100, 133, 20))
        self.sdText.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(255, 255, 255);")
        self.sdText.setObjectName("sdText")
        self.cityText = QtWidgets.QLineEdit(self.frame)
        self.cityText.setGeometry(QtCore.QRect(230, 100, 141, 20))
        self.cityText.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(255, 255, 255);")
        self.cityText.setObjectName("cityText")
        self.sText = QtWidgets.QLineEdit(self.frame)
        self.sText.setGeometry(QtCore.QRect(50, 160, 133, 20))
        self.sText.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(255, 255, 255);")
        self.sText.setObjectName("sText")
        self.zcText = QtWidgets.QLineEdit(self.frame)
        self.zcText.setGeometry(QtCore.QRect(230, 160, 141, 20))
        self.zcText.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(255, 255, 255);")
        self.zcText.setObjectName("zcText")
        self.search.raise_()
        self.delete_2.raise_()
        self.add.raise_()
        self.toAdminUI.raise_()
        self.nameText.raise_()
        self.numberText.raise_()
        self.sdText.raise_()
        self.cityText.raise_()
        self.sText.raise_()
        self.zcText.raise_()
        self.label_8 = QtWidgets.QLabel(proForm)
        self.label_8.setGeometry(QtCore.QRect(30, 0, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(proForm)
        self.label_9.setGeometry(QtCore.QRect(210, 0, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(proForm)
        self.label_10.setGeometry(QtCore.QRect(30, 60, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(proForm)
        self.label_11.setGeometry(QtCore.QRect(210, 60, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(proForm)
        self.label_12.setGeometry(QtCore.QRect(30, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(proForm)
        self.label_13.setGeometry(QtCore.QRect(210, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_13.setObjectName("label_13")

        self.retranslateUi(proForm)
        QtCore.QMetaObject.connectSlotsByName(proForm)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Member"))
        self.search.setText(_translate("Form", "search by number"))
        self.delete_2.setText(_translate("Form", "delete by number"))
        self.add.setText(_translate("Form", "add"))
        self.toAdminUI.setText(_translate("Form", "return"))
        self.label_8.setText(_translate("Form", "Member name:"))
        self.label_9.setText(_translate("Form", "Member number:"))
        self.label_10.setText(_translate("Form", "Member street address:"))
        self.label_11.setText(_translate("Form", "Member city:"))
        self.label_12.setText(_translate("Form", "Member state:"))
        self.label_13.setText(_translate("Form", "Member ZIP code:"))

import image_rc
