# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serviceDetail.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_srForm(object):
    def setupUi(self, sdForm):
        sdForm.setObjectName("srForm")
        sdForm.resize(383, 288)
        self.frame = QtWidgets.QFrame(sdForm)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 421, 371))
        self.frame.setStyleSheet("QFrame{\n"
" border-image:url(:/img/bg.jpg)\n"
"}\n"
"    \n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.mnText = QtWidgets.QLineEdit(self.frame)
        self.mnText.setGeometry(QtCore.QRect(220, 130, 133, 20))
        self.mnText.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(255, 255, 255);")
        self.mnText.setObjectName("mnText")
        self.pnText = QtWidgets.QLineEdit(self.frame)
        self.pnText.setGeometry(QtCore.QRect(30, 130, 133, 20))
        self.pnText.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(255, 255, 255);")
        self.pnText.setObjectName("pnText")
        self.scText = QtWidgets.QLineEdit(self.frame)
        self.scText.setGeometry(QtCore.QRect(30, 200, 133, 20))
        self.scText.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(255, 255, 255);")
        self.scText.setObjectName("scText")
        self.cText = QtWidgets.QLineEdit(self.frame)
        self.cText.setGeometry(QtCore.QRect(220, 200, 133, 20))
        self.cText.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(255, 255, 255);")
        self.cText.setObjectName("cText")
        self.addServiceRecord = QtWidgets.QPushButton(self.frame)
        self.addServiceRecord.setGeometry(QtCore.QRect(30, 250, 75, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.addServiceRecord.setFont(font)
        self.addServiceRecord.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(85, 85, 255);color: rgb(255, 255, 255);")
        self.addServiceRecord.setObjectName("addServiceRecord")
        self.toUserConUI = QtWidgets.QPushButton(self.frame)
        self.toUserConUI.setGeometry(QtCore.QRect(220, 250, 75, 23))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.toUserConUI.setFont(font)
        self.toUserConUI.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(85, 85, 255);color: rgb(255, 255, 255);")
        self.toUserConUI.setObjectName("toUserConUI")
        self.mnText.raise_()
        self.pnText.raise_()
        self.scText.raise_()
        self.cText.raise_()
        self.addServiceRecord.raise_()
        self.toUserConUI.raise_()
        self.label_7 = QtWidgets.QLabel(sdForm)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(sdForm)
        self.label_3.setGeometry(QtCore.QRect(210, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(sdForm)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(sdForm)
        self.label.setGeometry(QtCore.QRect(210, 90, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(sdForm)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(sdForm)
        self.label_5.setGeometry(QtCore.QRect(210, 150, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_5.setObjectName("label_5")
        self.cdatText = QtWidgets.QLineEdit(sdForm)
        self.cdatText.setGeometry(QtCore.QRect(20, 60, 133, 20))
        self.cdatText.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(255, 255, 255);")
        self.cdatText.setObjectName("cdatText")
        self.sdText = QtWidgets.QLineEdit(sdForm)
        self.sdText.setGeometry(QtCore.QRect(210, 60, 133, 20))
        self.sdText.setStyleSheet("border:2px rgb(85, 85, 255);border-radius:10px;padding:2px 4px;background-color:rgb(255, 255, 255);")
        self.sdText.setObjectName("sdText")

        self.retranslateUi(sdForm)
        QtCore.QMetaObject.connectSlotsByName(sdForm)

    def retranslateUi(self, srForm):
        _translate = QtCore.QCoreApplication.translate
        srForm.setWindowTitle(_translate("srForm", "Service Detail"))
        self.addServiceRecord.setText(_translate("srForm", "add"))
        self.toUserConUI.setText(_translate("srForm", "return"))
        self.label_7.setText(_translate("srForm", "Current date and time:"))
        self.label_3.setText(_translate("srForm", "Service date:"))
        self.label_4.setText(_translate("srForm", "Provider number:"))
        self.label.setText(_translate("srForm", "Member number:"))
        self.label_2.setText(_translate("srForm", "Service code:"))
        self.label_5.setText(_translate("srForm", "Comments:"))

import image_rc
